spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  config:
    import: optional:file:.env[.properties]
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

storage:
  directory: ${storage}
server:
  error:
    include-message: always
  port: ${port:8080}
token:
  secret: ${JWT_SECRET}
  expirationMinutes: 60
  refreshExpirationHours: 168
timeweb:
  s3:
    url: ${s3-url}
    bucket: ${s3-bucket}
    region: ${s3-region}
    access-key: ${s3-accesskey}
    secret-key: ${s3-secretkey}

logging:
  file:
    name: logs/app.log
#  level:
#    web: info

