version: "3.9"
services:
  animusic_db:
    container_name: animusic_postgres
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - type: bind
        source: ./database/data
        target: /var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d animusic' ]
      start_period: 10s
      interval: 20s
      timeout: 5s
      retries: 5
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - "5432:5432"

  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      db-url: jdbc:postgresql://animusic_db:5432/animusic
      port: 8081
      audio-path: "/animusic/audio"
      image_path: "/animusic/audio"
    volumes:
      - ${IMAGE_FOLDER}:/animusic/audio}
    ports:
      - "8081:8081"
    depends_on:
      animusic_db:
        condition: service_healthy
