version: "3.9"
services:
  animusic-db:
    container_name: animusic_postgres
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - type: bind
        source: ./database/data
        target: /var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d animusic' ]
      start_period: 10s
      interval: 20s
      timeout: 5s
      retries: 5
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - "5433:5432"

  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      db-url: jdbc:postgresql://animusic-db:5432/animusic
      port: 8081
      storage: "/animusic"
    volumes:
      - ${STORAGE}:/animusic
    ports:
      - "8081:8081"
    depends_on:
      animusic-db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

