services:
  db:
    image: postgres:14.5
    container_name : postgres_container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
  spring-app:
    container_name: spring-app
    build:
      context: /Users/admin/IdeaProjects/animusic
      dockerfile: Dockerfile
    environment:
      db-url: jdbc:postgresql://db:5432/animusic
      port: 8081
    ports:
      - 8081:8081
    depends_on:
      - db