version: "3.9"
services:
  animusic-db:
    container_name: animusic_postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=animusic
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U test -d animusic' ]
      start_period: 10s
      interval: 20s
      timeout: 5s
      retries: 5
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - "5433:5432"

  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://animusic-db:5432/animusic
      STORAGE_URL: http://storage:9000
      STORAGE_PUBLIC_URL: ${STORAGE_PUBLIC_URL}
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      animusic-db:
        condition: service_healthy

#  storage:
#    image: minio/minio
#    command: server /data --console-address :9001
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - '~/Animusic/Storage:/data'
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin
#      - MINIO_DEFAULT_BUCKETS=animusic

