scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

#        global:
#          scrape_interval: 5s
#          external_labels:
#            monitor: 'codelab-monitor'
#
#        scrape_configs:
#          - job_name: 'media-service'
#            scrape_interval: 5s
#            metrics_path: '/actuator/prometheus'
#            static_configs:
#              - targets: [ 'host.docker.internal:8081' ]