name: Deploy to production

on:
  pull_request:
    branches:
      - main

jobs:
  backend-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml -DskipTests
      - name: Run tests
        run: mvn test --file backend/pom.xml -Dspring.profiles.active=testing
  backend-deploy:
    runs-on: ubuntu-latest
    needs: backend-build-test
    steps:
      - name: Deploy backend to animusic.me
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_ANIMUSIC_USER }}
          host: ${{ secrets.SSH_ANIMUSIC_HOST }}
          key: ${{ secrets.SSH_ANIMUSIC_KEY }}
          port: 22
          script: |
            whoami
            cd ~/animusic
            ls -l
    
